spring:
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: true
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
        url: ${DATABASE_URL}


jwt:
    private.key: classpath:private_key.pem
    public.key: classpath:public_key.pem
