spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true