spring:
    jpa:
        hibernate:
            ddl-auto: update
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
        url: ${DATABASE_URL}