spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: on
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}