spring:
    datasource:
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        url: ${DB_URL}
    mail:
        host: ${MAIL_HOST}
        port: ${MAIL_PORT}
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}

cors:
    allowed-origin: https://vino-vibes.com

springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui/index.html